/**
 * parsePriceSheet.ts
  *
   * Parses an uploaded supplier document (CSV, Excel, or text-based price sheet)
    * and upserts the extracted rows into the `price_sheets` table via Prisma.
     *
      * The parser supports two document formats:
       *  1. CSV / TSV files – rows are read directly.
        *  2. Excel (.xlsx / .xls) files – first sheet is used (requires `xlsx` package).
         *
          * Expected column names (case-insensitive, flexible aliases):
           *   species         – wood species name (e.g. "Hard Maple", "Red Oak")
            *   grade           – lumber grade (e.g. "FAS", "Select", "#1 Common")
             *   thickness       – thickness expressed as quarters (e.g. "4/4", "8/4", or integer 4)
              *   price           – price per board-foot (numeric, e.g. "4.75")
               *   width_qualifier – optional width qualifier (e.g. "6\"&up", "wide")
                *
                 * The parser is deliberately lenient: rows with missing required fields are
                  * skipped and reported in the `errors` array returned to the caller.
                   */

                   import { prisma } from '@/lib/prisma';

                   // ---------------------------------------------------------------------------
                   // Types
                   // ---------------------------------------------------------------------------

                   export interface ParsePriceSheetOptions {
                     supplierId: number;
                       documentId: number;
                         fileUrl: string;
                           fileName: string;
                           }

                           export interface ParsePriceSheetResult {
                             inserted: number;
                               updated: number;
                                 total: number;
                                   errors: string[];
                                   }

                                   interface RawRow {
                                     species?: string;
                                       grade?: string;
                                         thickness?: string | number;
                                           price?: string | number;
                                             width_qualifier?: string;
                                               [key: string]: unknown;
                                               }

                                               // ---------------------------------------------------------------------------
                                               // Column-name aliases
                                               // ---------------------------------------------------------------------------

                                               const SPECIES_ALIASES = ['species', 'wood', 'wood species', 'item', 'description'];
                                               const GRADE_ALIASES = ['grade', 'quality', 'grading'];
                                               const THICKNESS_ALIASES = ['thickness', 'thick', 'thk', 'thickness (quarters)', 'quarters'];
                                               const PRICE_ALIASES = ['price', 'price/bf', 'price per bf', 'unit price', 'cost', '$/bf', 'rate'];
                                               const WIDTH_ALIASES = ['width qualifier', 'width_qualifier', 'width', 'widths', 'width note'];

                                               function findCol(headers: string[], aliases: string[]): string | undefined {
                                                 const lower = aliases.map((a) => a.toLowerCase());
                                                   return headers.find((h) => lower.includes(h.toLowerCase()));
                                                   }

                                                   // ---------------------------------------------------------------------------
                                                   // Thickness normalisation: convert "4/4", "8/4", "4" → integer quarters
                                                   // ---------------------------------------------------------------------------

                                                   function parseThickness(raw: string | number | undefined): number | null {
                                                     if (raw === undefined || raw === null || raw === '') return null;
                                                       const s = String(raw).trim();
                                                         // Fraction form: "4/4", "8/4" etc.
                                                           const fracMatch = s.match(/^(\d+)\s*\/\s*4$/);
                                                             if (fracMatch) return parseInt(fracMatch[1], 10);
                                                               // Plain integer
                                                                 const num = parseInt(s, 10);
                                                                   if (!isNaN(num) && num > 0) return num;
                                                                     return null;
                                                                     }

                                                                     // ---------------------------------------------------------------------------
                                                                     // Price normalisation: strip "$", commas, whitespace
                                                                     // ---------------------------------------------------------------------------

                                                                     function parsePrice(raw: string | number | undefined): number | null {
                                                                       if (raw === undefined || raw === null || raw === '') return null;
                                                                         const s = String(raw).replace(/[$,\s]/g, '');
                                                                           const n = parseFloat(s);
                                                                             return isNaN(n) ? null : n;
                                                                             }

                                                                             // ---------------------------------------------------------------------------
                                                                             // CSV row parser (handles quoted fields)
                                                                             // ---------------------------------------------------------------------------

                                                                             function parseCSVLine(line: string): string[] {
                                                                               const result: string[] = [];
                                                                                 let current = '';
                                                                                   let inQuotes = false;
                                                                                     for (let i = 0; i < line.length; i++) {
                                                                                         const ch = line[i];
                                                                                             if (ch === '"') {
                                                                                                   if (inQuotes && line[i + 1] === '"') {
                                                                                                           current += '"';
                                                                                                                   i++;
                                                                                                                         } else {
                                                                                                                                 inQuotes = !inQuotes;
                                                                                                                                       }
                                                                                                                                           } else if ((ch === ',' || ch === '\t') && !inQuotes) {
                                                                                                                                                 result.push(current);
                                                                                                                                                       current = '';
                                                                                                                                                           } else {
                                                                                                                                                                 current += ch;
                                                                                                                                                                     }
                                                                                                                                                                       }
                                                                                                                                                                         result.push(current);
                                                                                                                                                                           return result;
                                                                                                                                                                           }
                                                                                                                                                                           
                                                                                                                                                                           function csvToRows(text: string): RawRow[] {
                                                                                                                                                                             const lines = text.split(/\r?\n/).filter((l) => l.trim() !== '');
                                                                                                                                                                               if (lines.length < 2) return [];
                                                                                                                                                                               
                                                                                                                                                                                 const headers = parseCSVLine(lines[0]).map((h) => h.trim());
                                                                                                                                                                                   const rows: RawRow[] = [];
                                                                                                                                                                                   
                                                                                                                                                                                     for (let i = 1; i < lines.length; i++) {
                                                                                                                                                                                         const values = parseCSVLine(lines[i]);
                                                                                                                                                                                             const row: RawRow = {};
                                                                                                                                                                                                 headers.forEach((h, idx) => {
                                                                                                                                                                                                       row[h] = values[idx]?.trim() ?? '';
                                                                                                                                                                                                           });
                                                                                                                                                                                                               rows.push(row);
                                                                                                                                                                                                                 }
                                                                                                                                                                                                                   return rows;
                                                                                                                                                                                                                   }
                                                                                                                                                                                                                   
                                                                                                                                                                                                                   // ---------------------------------------------------------------------------
                                                                                                                                                                                                                   // Excel parser (dynamic import so it doesn't break if xlsx not installed)
                                                                                                                                                                                                                   // ---------------------------------------------------------------------------
                                                                                                                                                                                                                   
                                                                                                                                                                                                                   async function excelToRows(buffer: ArrayBuffer): Promise<RawRow[]> {
                                                                                                                                                                                                                     try {
                                                                                                                                                                                                                         // `xlsx` is a common package already used in many Next.js projects.
                                                                                                                                                                                                                             // If not installed, this will throw and we fall back gracefully.
                                                                                                                                                                                                                                 const XLSX = await import('xlsx' as any);
                                                                                                                                                                                                                                     const workbook = XLSX.read(new Uint8Array(buffer), { type: 'array' });
                                                                                                                                                                                                                                         const sheetName = workbook.SheetNames[0];
                                                                                                                                                                                                                                             if (!sheetName) return [];
                                                                                                                                                                                                                                                 const sheet = workbook.Sheets[sheetName];
                                                                                                                                                                                                                                                     return XLSX.utils.sheet_to_json(sheet, { defval: '' }) as RawRow[];
                                                                                                                                                                                                                                                       } catch {
                                                                                                                                                                                                                                                           throw new Error(
                                                                                                                                                                                                                                                                 'Failed to parse Excel file. Make sure the `xlsx` package is installed (`npm install xlsx`).'
                                                                                                                                                                                                                                                                     );
                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                       // ---------------------------------------------------------------------------
                                                                                                                                                                                                                                                                       // Main entry point
                                                                                                                                                                                                                                                                       // ---------------------------------------------------------------------------
                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                       export async function parsePriceSheet(
                                                                                                                                                                                                                                                                         opts: ParsePriceSheetOptions
                                                                                                                                                                                                                                                                         ): Promise<ParsePriceSheetResult> {
                                                                                                                                                                                                                                                                           const { supplierId, fileUrl, fileName } = opts;
                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                             // 1. Download the file from Supabase storage
                                                                                                                                                                                                                                                                               const resp = await fetch(fileUrl);
                                                                                                                                                                                                                                                                                 if (!resp.ok) {
                                                                                                                                                                                                                                                                                     throw new Error(`Failed to download document from storage: ${resp.status} ${resp.statusText}`);
                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                         const buffer = await resp.arrayBuffer();
                                                                                                                                                                                                                                                                                           const lowerName = fileName.toLowerCase();
                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                             // 2. Parse into raw rows depending on file type
                                                                                                                                                                                                                                                                                               let rawRows: RawRow[] = [];
                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                 if (lowerName.endsWith('.csv') || lowerName.endsWith('.tsv')) {
                                                                                                                                                                                                                                                                                                     const text = new TextDecoder().decode(buffer);
                                                                                                                                                                                                                                                                                                         rawRows = csvToRows(text);
                                                                                                                                                                                                                                                                                                           } else if (lowerName.endsWith('.xlsx') || lowerName.endsWith('.xls')) {
                                                                                                                                                                                                                                                                                                               rawRows = await excelToRows(buffer);
                                                                                                                                                                                                                                                                                                                 } else {
                                                                                                                                                                                                                                                                                                                     // Last resort: try to decode as CSV/TSV text
                                                                                                                                                                                                                                                                                                                         const text = new TextDecoder().decode(buffer);
                                                                                                                                                                                                                                                                                                                             rawRows = csvToRows(text);
                                                                                                                                                                                                                                                                                                                                 if (rawRows.length === 0) {
                                                                                                                                                                                                                                                                                                                                       throw new Error(
                                                                                                                                                                                                                                                                                                                                               `Unsupported file format: ${fileName}. Please upload a CSV or Excel file.`
                                                                                                                                                                                                                                                                                                                                                     );
                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                             if (rawRows.length === 0) {
                                                                                                                                                                                                                                                                                                                                                                 return { inserted: 0, updated: 0, total: 0, errors: ['No data rows found in document.'] };
                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                     // 3. Identify columns
                                                                                                                                                                                                                                                                                                                                                                       const headers = Object.keys(rawRows[0]);
                                                                                                                                                                                                                                                                                                                                                                         const speciesCol = findCol(headers, SPECIES_ALIASES);
                                                                                                                                                                                                                                                                                                                                                                           const gradeCol = findCol(headers, GRADE_ALIASES);
                                                                                                                                                                                                                                                                                                                                                                             const thicknessCol = findCol(headers, THICKNESS_ALIASES);
                                                                                                                                                                                                                                                                                                                                                                               const priceCol = findCol(headers, PRICE_ALIASES);
                                                                                                                                                                                                                                                                                                                                                                                 const widthCol = findCol(headers, WIDTH_ALIASES);
                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                   const missingCols: string[] = [];
                                                                                                                                                                                                                                                                                                                                                                                     if (!speciesCol) missingCols.push('species');
                                                                                                                                                                                                                                                                                                                                                                                       if (!thicknessCol) missingCols.push('thickness');
                                                                                                                                                                                                                                                                                                                                                                                         if (!priceCol) missingCols.push('price');
                                                                                                                                                                                                                                                                                                                                                                                           if (missingCols.length > 0) {
                                                                                                                                                                                                                                                                                                                                                                                               throw new Error(
                                                                                                                                                                                                                                                                                                                                                                                                     `Required columns not found in document: ${missingCols.join(', ')}. ` +
                                                                                                                                                                                                                                                                                                                                                                                                             `Available columns: ${headers.join(', ')}`
                                                                                                                                                                                                                                                                                                                                                                                                                 );
                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                     // 4. Process rows
                                                                                                                                                                                                                                                                                                                                                                                                                       let inserted = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                         let updated = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                           const errors: string[] = [];
                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                             for (let i = 0; i < rawRows.length; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                 const row = rawRows[i];
                                                                                                                                                                                                                                                                                                                                                                                                                                     const rowNum = i + 2; // 1-indexed, +1 for header row
                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                         const species = String(row[speciesCol!] ?? '').trim();
                                                                                                                                                                                                                                                                                                                                                                                                                                             const grade = gradeCol ? String(row[gradeCol] ?? '').trim() : 'Unknown';
                                                                                                                                                                                                                                                                                                                                                                                                                                                 const thicknessRaw = row[thicknessCol!];
                                                                                                                                                                                                                                                                                                                                                                                                                                                     const priceRaw = row[priceCol!];
                                                                                                                                                                                                                                                                                                                                                                                                                                                         const widthQualifier = widthCol ? String(row[widthCol] ?? '').trim() || null : null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                             if (!species) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   errors.push(`Row ${rowNum}: skipped – species is empty.`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         continue;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const thicknessQuarters = parseThickness(thicknessRaw as string | number);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (thicknessQuarters === null) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           errors.push(`Row ${rowNum}: skipped – invalid thickness "${thicknessRaw}".`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 continue;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         const pricePerBf = parsePrice(priceRaw as string | number);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             if (pricePerBf === null) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   errors.push(`Row ${rowNum}: skipped – invalid price "${priceRaw}".`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         continue;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // 5. Upsert into price_sheets using the unique constraint
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           const existing = await prisma.priceSheet.findFirst({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   where: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             supplierId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       species,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 grade: grade || 'Unknown',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           thicknessQuarters,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     widthQualifier: widthQualifier ?? null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if (existing) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 await prisma.priceSheet.update({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           where: { id: existing.id },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     data: { pricePerBf },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     updated++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   await prisma.priceSheet.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             data: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         supplierId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     species,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 grade: grade || 'Unknown',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             thicknessQuarters,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         pricePerBf,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     widthQualifier: widthQualifier ?? null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               inserted++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         } catch (dbErr: any) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               errors.push(`Row ${rowNum}: DB error – ${dbErr?.message ?? 'unknown error'}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           inserted,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               updated,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   total: inserted + updated,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       errors,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
